### ISSUE TITLE
[Bug]: python setup fails in the centos

### ISSUE THREAD

**Issue by karthik-philips-ta** [insightsengineering/presidio-action#10]
### What happened?

The action fails to install python looks like python setup action which being used works only on ubuntu OS, we are having centos runners for which it fails to install.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by cicdguy** [comment]
Thanks for the report @karthik-philips-ta. We will investigate and look into a fix for this.
